name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: sudo apt install -y clang mold libwayland-dev libxkbcommon-dev librust-alsa-sys-dev
      - name: Run tests
        run: cargo test --release
      - name: Build
        run: cargo build --release
